name: sync

on:
  workflow_dispatch:
  schedule:
    - cron: '0 */4 * * *'
    
jobs:
  build:
    runs-on: ubuntu-latest
    if: ${{ github.event.repository.owner.id == github.event.sender.id && github.repository == 'FUXKTME/jd_scripts' }}
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
    - name: Init Build Dependencies
      env:
        DEBIAN_FRONTEND: noninteractive
      run: |
        sudo -E rm -rf /etc/apt/sources.list.d
        sudo -E apt-get update -y && apt-get install -y build-essential git git-core curl wget && apt-get clean -y
        git config --global user.name 'GitHub Actions' && git config --global user.email 'noreply@github.com'

    - name: Prepare
      run: |
        mkdir -p ~/.ssh
        echo -e "${{ secrets.SSH_KEY }}" > ~/.ssh/id_rsa
        chmod 600 ~/.ssh/id_rsa
        ssh-keyscan gitee.com > ~/.ssh/known_hosts
        
    - name: repo-sync
      uses: repo-sync/github-sync@v2
      with:
        source_repo: "git@gitee.com:lxk0301/jd_scripts.git"
        source_branch: "master"
        destination_branch: "master"
        github_token: ${{ secrets.TOKEN }}
        
