# repo-sync.yml

on:
  schedule:
  - cron:  "*/30 * * * *"
  workflow_dispatch:

jobs:
  repo-sync:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
      with:
        persist-credentials: false
        access_token: ${{ secrets.PAT }}
    - name: GitHub Repo Sync
      uses: repo-sync/github-sync@v2.3.0
      with:
        source_repo: "https://FuxkTME:${access_token}@github.com/FuxkTME/repository.git"
        source_branch: "master"
        destination_branch: "tencent"
        github_token: ${{ secrets.PAT }}
